<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <script>

        console.log(1);
        console.log(2);
       
        //questa promise gestisce un caso in cui l'insuccesso è previsto
        let call  = new Promise(function(success, error) {
            
            setTimeout(function(){//stiamo simulando l'attesa del server

                let password = 'password';
                if(password == 'passwords'){
                    success('Accesso consentito');
                }else{
                    error('C\'è stato un errore');
                }
            }, 3000)
        })
        
        call.then(
            (risultato)=>console.log(risultato),
            (erroreRisultato)=>console.log(erroreRisultato)
         );
        
        console.log(3);


        //non è obbligatorio inserire anche la callback per l'errore
        let call2 = new Promise(function(success) {
            success('Ecco il risultato')
        })

        call2.then((res)=>console.log(res))

    </script>
</body>
</html>